### ISSUE TITLE
Wrong domain in model.UriBase

### ISSUE THREAD

**Issue by bs-oke** [CatalystCode/botbuilder-instrumentation-cs#10]
I've an issue in LUIS authorization (Exception: Response status code does not indicate success: 401 (Access Denied).). I was looking around and I found one thing:

My LUIS is in westeurope.api.cognitive.microsoft.com domain, I set LuisModel domain to it and so CognitiveServiceApiEndpoint. But when I run the app I get "https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/" in model.UriBase.  ModelID and SubscriptionKey are ok. I've no "westus.api.cognitive.microsoft.com" anywhere in my app.

**Comment by itye-msft** [comment]
@bs-oke Thanks for the feedback. The error occued because the endpoint is hard coded.
We will soon push a fix to address this issue.
Please stay tuned.
Thanks 
Itye

**Comment by itye-msft** [comment]
Hi @bs-oke 

Since you are using cognitive service and LUIS, you need to add the following keys to your web.config:
```xml
    <!-- LUIS credentials-->
    <add key="LuisModelId" value="your LUIS model URL" />
    <add key="LuisSubscriptionKey" value="subscription key" />
    
    <!-- Text Analytics data for message sentiment analysis -->
    <add key="TextAnalyticsApiKey" value="text analytics api key" />
    <add key="TextAnalyticsMinLength" value="3" />
    <add key="CognitiveServiceApiEndpoint" value="https://westus.api.cognitive.microsoft.com/"/>
```
* `TextAnalyticsApiKey`. To track sentiment analysis, the telemetry code calls the Text Analytics API, you can obtain this key from the Azure Portal. The bot won't log any sentiment data if this value is empty.
* `TextAnalyticsMinLength`. You normally don't want to track sentiment for short phrases like "yes", "no", etc. In the example above, this parameter tells the logger to only track sentiment for messages that have 3 words or more. 
* 'CognitiveServiceApiEndpoint' allows you to set the correct region for cognitive services.
**This is the key you should probably edit.**

Let me know if it helped.
Thanks
Itye

**Comment by bs-oke** [comment]
Hi @itye-msft 

Thanks for your replay.

I have it in my config:
```
    <!-- Text Analytics data for message sentiment analysis -->
    <add key="TextAnalyticsApiKey" value= <proper key is here> />
    <add key="TextAnalyticsMinLenght" value="3" />
    <add key="CognitiveServiceApiEndpoint" value="https://westeurope.api.cognitive.microsoft.com/" />
```
And it doesn't help.

Kind regards
Bartek

**Comment by itye-msft** [comment]
@bs-oke 
Are you instantiating the instrumentation using the built in dependency resolver, or using your custom code?
The provided dependency resolver in this code sample is the only place where the we read the confing file. It means, that if you are using your own code, you should make sure to correctly instantiate `SentimentManager`.

The code does not contain any hard coded URLs such as the one that appears in your error. Everything it being called from the config file. Can you verify it by debugging it?

**Comment by bs-oke** [comment]
@itye-msft 
I have copied solution from your Bot-with-instrumentation-cs example so I use InstrumentationHelper class and instantiate the instrumentation from HandleSystemMessage.

When I stop at `await InstrumentationHelper.DefaultInstrumentation.TrackActivity(message);` in `MessageController.HandleSystemMessage` I have a proper _cognitiveServiceApiEndpoint (`https://westeurope.api.cognitive.microsoft.com/`). But when I say something to a bot and stop in `public RootDialog()` I have wrong endpoint in services-model-UriBase (`westus.api.cognitive.microsoft.com`) and in the next step I get exception in 'MessageController.Post' (`Response status code does not indicate success: 401 (Access Denied).`).

For LUIS credentials I use Id and key from Endpoint Url which work fine outside the bot. For `TextAnalyticsApiKey` I use one of LUIS' Keys taken from Azure (hope it's ok).

**Comment by itye-msft** [comment]
@bs-oke 
I have verified that none of the repos contains `westus.api.cognitive.microsoft.com` string.
Can you please attach your complete code? I will try to debug it with the sources directly.
Otherwise, based on what you wrote it should have worked, and the only way I can suggest to nail the problem is by debugging it.

Thanks
Itye

**Comment by bs-oke** [comment]
@itye-msft 
OK, thanks, but I'm not sure if I want to publish my code with all credentials. Is there any way to send it directly to you?

**Comment by itye-msft** [comment]
@bs-oke please send it to: itye.richter@microsoft.com

**Comment by bs-oke** [comment]
Because problem was solved outside this issue tracking (thanks @itye-msft!) I'm showing only what's changed to make things work (according to changes made in BotBuilder Instrumentation):

### Web.config
`LuisDomain` added
```
    <!-- LUIS credentials-->
    <add key="LuisModelId" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" />
    <add key="LuisSubscriptionKey" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" />
    <add key="LuisDomain" value="westeurope.api.cognitive.microsoft.com" />
```
### RootDialog.cs
`LuisDomain` added
```
        public RootDialog() : 
            base(ConfigurationManager.AppSettings["LuisModelId"], 
                ConfigurationManager.AppSettings["LuisSubscriptionKey"], 
                ConfigurationManager.AppSettings["LuisDomain"])
        {
        }
```
