### ISSUE TITLE
Method not found exception

### ISSUE THREAD

**Issue by youtoofan** [CatalystCode/botbuilder-instrumentation-cs#12]
The latest version of the botbuilder package is throwing an exception:
`Method not found: 'System.Nullable`1<System.DateTime> Microsoft.Bot.Connector.IActivity.get_Timestamp()'.`

This is the stacktrace:
`   at BotBuilder.Instrumentation.BotFrameworkApplicationInsightsInstrumentation.BuildEventTelemetry(IActivity activity, IDictionary`2 properties, IDictionary`2 metrics)
   at BotBuilder.Instrumentation.BotFrameworkApplicationInsightsInstrumentation.TrackLuisIntent(IActivity activity, LuisResult result)
   at VTChatbot.Dialogs.BasicLuisDialog.DispatchToIntentHandler(IDialogContext context, IAwaitable`1 item, IntentRecommendation bestIntent, LuisResult result) in C:\_TFSRemote\VT Chatbot\src\dev\VTChatbot\Dialogs\BasicLuisDialog.cs`

When I install version 3.8.3.0 of the Microsoft.Bot.Builder package, I don't get the exception.

**Comment by morsh** [comment]
This is probably since the latest version has breaking changes.
Unfortunately, this is a sample repository so we are not actively maintaining it. But if you wish to submit a PR with the fix, we'll be able to review and approve it.

**Comment by youtoofan** [comment]
I fixed it by upgrading to the latest Microsoft.Bot.Builder version and updated the timestamp property in the BuildEventTelemetry method.

**Comment by morsh** [comment]
@youtoofan - would be happy if you could submit a PR with the fix, if that's at all possible :)

**Comment by mirkon90** [comment]
Do you have any updates about the pull request?
Coming from the issue #13, I also encountered the same problem (BotBuilder SDK 3.14.0.7)

**Comment by morsh** [comment]
Hi @mirkon90 - I didn't get any PR on that
